### ISSUE TITLE
Traceback in atexit._run_exitfuncs

### ISSUE THREAD

**Issue by pcahyna** [linux-system-roles/test-harness#51] opened 2019-03-19 10:34 UTC
https://larsu.fedorapeople.org/logs/linux-system-roles-storage-pull-linux-system-roles_storage-17-a7bb149-centos-7-20190318-194801/artifacts/ansible.log

>  [ERROR]: Error in atexit._run_exitfuncs: Traceback (most recent call last):
> File "/usr/share/ansible/inventory/standard-inventory-qcow2", line 121, in
> cleanup     fullname = os.path.join(tempfile['path'], tempfile['file'].name)
> File "/usr/lib64/python3.6/posixpath.py", line 80, in join     a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not NoneType

Just before, there is
> /usr/share/ansible/inventory/standard-inventory-qcow2 did not meet host_list requirements, check plugin documentation if this is unexpected

not sure whether this is related.

**Comment by pcahyna** [comment] 2020-02-05 14:36
I think t is fixed in https://pagure.io/standard-test-roles/c/354ae9b576798ae0cbbf6898269a132140b5d3c5?branch=master so we just need an updated version of standard-test-roles.

**Comment by richm** [comment] 2020-04-01 23:17
I can't reproduce - can we close this?

**Comment by pcahyna** [comment] 2020-04-02 08:15
what version of `standard-inventory-qcow2` do we have now?

**Comment by richm** [comment] 2020-04-02 13:37
> what version of `standard-inventory-qcow2` do we have now?

standard-test-roles-inventory-qemu-4.5-3.fc31.noarch

**Comment by richm** [comment] 2020-06-23 21:56
I'm assuming this has been fixed in an update.  Closing.  Please open a new issue if can be reproduced.

**Closed by richm** 2020-06-23 21:56 UTC
